{{- if .Values.server.podDisruptionBudget.enabled }}
{{- $pdb := .Values.server.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-server" (include "authentik.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      {{- include "authentik.server.selectorLabels" . | nindent 6 }}
  {{- if $pdb.minAvailable }}
  minAvailable: {{ $pdb.minAvailable }}
  {{- end }}
  {{- if $pdb.maxUnavailable }}
  maxUnavailable: {{ $pdb.maxUnavailable }}
  {{- end }}
{{- end }}
{{- if .Values.worker.podDisruptionBudget.enabled }}
{{- $pdb := .Values.worker.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-worker" (include "authentik.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  selector:
    matchLabels:
      {{- include "authentik.worker.selectorLabels" . | nindent 6 }}
  {{- if $pdb.minAvailable }}
  minAvailable: {{ $pdb.minAvailable }}
  {{- end }}
  {{- if $pdb.maxUnavailable }}
  maxUnavailable: {{ $pdb.maxUnavailable }}
  {{- end }}
{{- end }}
