{{- if .Values.server.metrics.serviceMonitor.enabled }}
{{- $sm := .Values.server.metrics.serviceMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-server" (include "authentik.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "authentik.server.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ $sm.interval }}
      scrapeTimeout: {{ $sm.scrapeTimeout }}
      path: /metrics
      {{- with $sm.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $sm.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
