{{- if include "postgresql.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ include "postgresql.namespace" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  {{- with merge .Values.commonAnnotations dict }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.enablePostgresUser }}
  {{- $postgresPassword := .Values.auth.postgresPassword | default (randAlphaNum 16) }}
  {{ .Values.auth.secretKeys.adminPasswordKey }}: {{ $postgresPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.username }}
  {{- $userPassword := .Values.auth.password | default (randAlphaNum 16) }}
  {{ .Values.auth.secretKeys.userPasswordKey }}: {{ $userPassword | b64enc | quote }}
  {{- end }}
  {{ .Values.auth.secretKeys.replicationPasswordKey }}: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
