apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.primary.fullname" . }}
  namespace: {{ include "postgresql.namespace" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  {{- with merge .Values.primary.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.primary.service.type }}
  {{- if and (eq .Values.primary.service.type "LoadBalancer") .Values.primary.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.primary.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: postgresql
      port: {{ .Values.primary.service.port }}
      targetPort: postgresql
      protocol: TCP
      {{- if and (eq .Values.primary.service.type "NodePort") .Values.primary.service.nodePort }}
      nodePort: {{ .Values.primary.service.nodePort }}
      {{- end }}
  selector:
    {{- include "postgresql.primary.selectorLabels" . | nindent 4 }}
