{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payload-cms.fullname" . }}
  namespace: {{ include "payload-cms.namespace" . }}
  labels:
    {{- include "payload-cms.labels" . | nindent 4 }}
type: Opaque
data:
  payload-secret: {{ .Values.auth.payloadSecret | b64enc | quote }}
  database-uri: {{ .Values.database.uri | b64enc | quote }}
{{- end }}
